// This file was automatically generated by TanStack Router.
// Manual additions for checkers routes added in 0004 integration.
import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedDashboardWalletRouteImport } from './routes/_authed/dashboard/wallet'
import { Route as AuthedDashboardHistoryRouteImport } from './routes/_authed/dashboard/history'
import { Route as AuthedDashboardCheckersIndexRouteImport } from './routes/_authed/dashboard/checkers/index'
import { Route as AuthedDashboardCheckersContestIdRouteImport } from './routes/_authed/dashboard/checkers/$contestId'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedAdminTransactionsRouteImport } from './routes/_authed/admin/transactions'
import { Route as AuthedAdminTrafficRouteImport } from './routes/_authed/admin/traffic'
import { Route as AuthedAdminSupportRouteImport } from './routes/_authed/admin/support'
import { Route as AuthedAdminPendingRouteImport } from './routes/_authed/admin/pending'
import { Route as AuthedAdminGamesRouteImport } from './routes/_authed/admin/games'
import { Route as AuthedAdminFinanceRouteImport } from './routes/_authed/admin/finance'
import { Route as AuthedAdminApprovalsRouteImport } from './routes/_authed/admin/approvals'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)

const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/_authed/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/_authed/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/_authed/dashboard/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)

const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/_authed/admin/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)

const AuthedDashboardWalletRoute = AuthedDashboardWalletRouteImport.update({
  id: '/_authed/dashboard/wallet',
  path: '/wallet',
  getParentRoute: () => AuthedDashboardRoute,
} as any)

const AuthedDashboardHistoryRoute = AuthedDashboardHistoryRouteImport.update({
  id: '/_authed/dashboard/history',
  path: '/history',
  getParentRoute: () => AuthedDashboardRoute,
} as any)

const AuthedDashboardCheckersIndexRoute = AuthedDashboardCheckersIndexRouteImport.update({
  id: '/_authed/dashboard/checkers/',
  path: '/checkers',
  getParentRoute: () => AuthedDashboardRoute,
} as any)

const AuthedDashboardCheckersContestIdRoute = AuthedDashboardCheckersContestIdRouteImport.update({
  id: '/_authed/dashboard/checkers/$contestId',
  path: '/checkers/$contestId',
  getParentRoute: () => AuthedDashboardRoute,
} as any)

const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/_authed/admin/users',
  path: '/users',
  getParentRoute: () => AuthedAdminRoute,
} as any)

const AuthedAdminTransactionsRoute = AuthedAdminTransactionsRouteImport.update({
  id: '/_authed/admin/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedAdminRoute,
} as any)

const AuthedAdminTrafficRoute = AuthedAdminTrafficRouteImport.update({
  id: '/_authed/admin/traffic',
  path: '/traffic',
  getParentRoute: () => AuthedAdminRoute,
} as any)

const AuthedAdminSupportRoute = AuthedAdminSupportRouteImport.update({
  id: '/_authed/admin/support',
  path: '/support',
  getParentRoute: () => AuthedAdminRoute,
} as any)

const AuthedAdminPendingRoute = AuthedAdminPendingRouteImport.update({
  id: '/_authed/admin/pending',
  path: '/pending',
  getParentRoute: () => AuthedAdminRoute,
} as any)

const AuthedAdminGamesRoute = AuthedAdminGamesRouteImport.update({
  id: '/_authed/admin/games',
  path: '/games',
  getParentRoute: () => AuthedAdminRoute,
} as any)

const AuthedAdminFinanceRoute = AuthedAdminFinanceRouteImport.update({
  id: '/_authed/admin/finance',
  path: '/finance',
  getParentRoute: () => AuthedAdminRoute,
} as any)

const AuthedAdminApprovalsRoute = AuthedAdminApprovalsRouteImport.update({
  id: '/_authed/admin/approvals',
  path: '/approvals',
  getParentRoute: () => AuthedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/wallet': typeof AuthedDashboardWalletRoute
  '/dashboard/history': typeof AuthedDashboardHistoryRoute
  '/dashboard/checkers': typeof AuthedDashboardCheckersIndexRoute
  '/dashboard/checkers/$contestId': typeof AuthedDashboardCheckersContestIdRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/admin/approvals': typeof AuthedAdminApprovalsRoute
  '/admin/finance': typeof AuthedAdminFinanceRoute
  '/admin/games': typeof AuthedAdminGamesRoute
  '/admin/pending': typeof AuthedAdminPendingRoute
  '/admin/support': typeof AuthedAdminSupportRoute
  '/admin/traffic': typeof AuthedAdminTrafficRoute
  '/admin/transactions': typeof AuthedAdminTransactionsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthedRoute: typeof AuthedRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  SigninRoute,
  SignupRoute,
  ForgotPasswordRoute,
  ResetPasswordRoute,
  AuthedRoute,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
