/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedDashboardWalletRouteImport } from './routes/_authed/dashboard/wallet'
import { Route as AuthedDashboardHistoryRouteImport } from './routes/_authed/dashboard/history'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedAdminTransactionsRouteImport } from './routes/_authed/admin/transactions'
import { Route as AuthedAdminTrafficRouteImport } from './routes/_authed/admin/traffic'
import { Route as AuthedAdminSupportRouteImport } from './routes/_authed/admin/support'
import { Route as AuthedAdminPendingRouteImport } from './routes/_authed/admin/pending'
import { Route as AuthedAdminGamesRouteImport } from './routes/_authed/admin/games'
import { Route as AuthedAdminFinanceRouteImport } from './routes/_authed/admin/finance'
import { Route as AuthedAdminApprovalsRouteImport } from './routes/_authed/admin/approvals'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedDashboardWalletRoute = AuthedDashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardHistoryRoute = AuthedDashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminTransactionsRoute = AuthedAdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminTrafficRoute = AuthedAdminTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminSupportRoute = AuthedAdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminPendingRoute = AuthedAdminPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminGamesRoute = AuthedAdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminFinanceRoute = AuthedAdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminApprovalsRoute = AuthedAdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/admin/approvals': typeof AuthedAdminApprovalsRoute
  '/admin/finance': typeof AuthedAdminFinanceRoute
  '/admin/games': typeof AuthedAdminGamesRoute
  '/admin/pending': typeof AuthedAdminPendingRoute
  '/admin/support': typeof AuthedAdminSupportRoute
  '/admin/traffic': typeof AuthedAdminTrafficRoute
  '/admin/transactions': typeof AuthedAdminTransactionsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/dashboard/history': typeof AuthedDashboardHistoryRoute
  '/dashboard/wallet': typeof AuthedDashboardWalletRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/approvals': typeof AuthedAdminApprovalsRoute
  '/admin/finance': typeof AuthedAdminFinanceRoute
  '/admin/games': typeof AuthedAdminGamesRoute
  '/admin/pending': typeof AuthedAdminPendingRoute
  '/admin/support': typeof AuthedAdminSupportRoute
  '/admin/traffic': typeof AuthedAdminTrafficRoute
  '/admin/transactions': typeof AuthedAdminTransactionsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/dashboard/history': typeof AuthedDashboardHistoryRoute
  '/dashboard/wallet': typeof AuthedDashboardWalletRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/_authed/admin/approvals': typeof AuthedAdminApprovalsRoute
  '/_authed/admin/finance': typeof AuthedAdminFinanceRoute
  '/_authed/admin/games': typeof AuthedAdminGamesRoute
  '/_authed/admin/pending': typeof AuthedAdminPendingRoute
  '/_authed/admin/support': typeof AuthedAdminSupportRoute
  '/_authed/admin/traffic': typeof AuthedAdminTrafficRoute
  '/_authed/admin/transactions': typeof AuthedAdminTransactionsRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/dashboard/history': typeof AuthedDashboardHistoryRoute
  '/_authed/dashboard/wallet': typeof AuthedDashboardWalletRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/admin/approvals'
    | '/admin/finance'
    | '/admin/games'
    | '/admin/pending'
    | '/admin/support'
    | '/admin/traffic'
    | '/admin/transactions'
    | '/admin/users'
    | '/dashboard/history'
    | '/dashboard/wallet'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/admin/approvals'
    | '/admin/finance'
    | '/admin/games'
    | '/admin/pending'
    | '/admin/support'
    | '/admin/traffic'
    | '/admin/transactions'
    | '/admin/users'
    | '/dashboard/history'
    | '/dashboard/wallet'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/_authed/admin'
    | '/_authed/dashboard'
    | '/_authed/admin/approvals'
    | '/_authed/admin/finance'
    | '/_authed/admin/games'
    | '/_authed/admin/pending'
    | '/_authed/admin/support'
    | '/_authed/admin/traffic'
    | '/_authed/admin/transactions'
    | '/_authed/admin/users'
    | '/_authed/dashboard/history'
    | '/_authed/dashboard/wallet'
    | '/_authed/admin/'
    | '/_authed/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/dashboard/wallet': {
      id: '/_authed/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AuthedDashboardWalletRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/history': {
      id: '/_authed/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof AuthedDashboardHistoryRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/transactions': {
      id: '/_authed/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthedAdminTransactionsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/traffic': {
      id: '/_authed/admin/traffic'
      path: '/traffic'
      fullPath: '/admin/traffic'
      preLoaderRoute: typeof AuthedAdminTrafficRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/support': {
      id: '/_authed/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthedAdminSupportRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/pending': {
      id: '/_authed/admin/pending'
      path: '/pending'
      fullPath: '/admin/pending'
      preLoaderRoute: typeof AuthedAdminPendingRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/games': {
      id: '/_authed/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AuthedAdminGamesRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/finance': {
      id: '/_authed/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthedAdminFinanceRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/approvals': {
      id: '/_authed/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthedAdminApprovalsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminApprovalsRoute: typeof AuthedAdminApprovalsRoute
  AuthedAdminFinanceRoute: typeof AuthedAdminFinanceRoute
  AuthedAdminGamesRoute: typeof AuthedAdminGamesRoute
  AuthedAdminPendingRoute: typeof AuthedAdminPendingRoute
  AuthedAdminSupportRoute: typeof AuthedAdminSupportRoute
  AuthedAdminTrafficRoute: typeof AuthedAdminTrafficRoute
  AuthedAdminTransactionsRoute: typeof AuthedAdminTransactionsRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminApprovalsRoute: AuthedAdminApprovalsRoute,
  AuthedAdminFinanceRoute: AuthedAdminFinanceRoute,
  AuthedAdminGamesRoute: AuthedAdminGamesRoute,
  AuthedAdminPendingRoute: AuthedAdminPendingRoute,
  AuthedAdminSupportRoute: AuthedAdminSupportRoute,
  AuthedAdminTrafficRoute: AuthedAdminTrafficRoute,
  AuthedAdminTransactionsRoute: AuthedAdminTransactionsRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedDashboardRouteChildren {
  AuthedDashboardHistoryRoute: typeof AuthedDashboardHistoryRoute
  AuthedDashboardWalletRoute: typeof AuthedDashboardWalletRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardHistoryRoute: AuthedDashboardHistoryRoute,
  AuthedDashboardWalletRoute: AuthedDashboardWalletRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
