-- ============================================================================
-- Migration: 0004_checkers_matchmaking.sql
-- Purpose:   Variant engine, theme manager, matchmaking/tournaments,
--            wallet verification, booking system, and daily trial quota
--            for the Checkers 3D game integration.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- ENUM EXTENSIONS
-- ----------------------------------------------------------------------------

-- Checkers rule variants
create type public.checkers_variant as enum ('english', 'russian');

-- Checkers board/coin themes (mirrors ThemeManager THEMES keys in Modules.js)
create type public.checkers_theme as enum ('classic', 'green', 'midnight', 'red', 'ivory');

-- Contest lifecycle: open → booked → in_progress → completed | cancelled
create type public.contest_status as enum ('open', 'booked', 'in_progress', 'completed', 'cancelled');

-- ----------------------------------------------------------------------------
-- CHECKERS CONTESTS
-- A contest is a hosted checkers match with a specific variant, theme, and
-- optional entry fee. 'open' means the host is waiting for an opponent.
-- 'booked' means both seats are filled and locked — no more joiners.
-- ----------------------------------------------------------------------------

create table public.checkers_contests (
  id              uuid primary key default gen_random_uuid(),
  host_id         uuid not null references public.profiles (id) on delete cascade,
  variant         public.checkers_variant not null default 'english',
  theme           public.checkers_theme not null default 'classic',

  -- Entry fee in KES cents. 0 = Free Trial match.
  entry_fee_cents bigint not null default 0 check (entry_fee_cents >= 0),

  -- Accumulated pot. For a 2-player game: 0 (free) or 2 × entry_fee_cents.
  pot_cents       bigint not null default 0 check (pot_cents >= 0),

  status          public.contest_status not null default 'open',

  -- Winner set on completion; null if cancelled or draw.
  winner_id       uuid references public.profiles (id),

  -- Room code for direct invite (6-char uppercase alphanum). Generated by trigger.
  room_code       text not null unique,

  created_at      timestamptz not null default now(),
  booked_at       timestamptz,
  started_at      timestamptz,
  completed_at    timestamptz
);

comment on table public.checkers_contests is
  'Hosted checkers contests. Each row is one 1v1 match with variant + theme + stake.';

create index checkers_contests_status_idx    on public.checkers_contests (status);
create index checkers_contests_host_idx      on public.checkers_contests (host_id);
create index checkers_contests_created_idx   on public.checkers_contests (created_at desc);

-- ----------------------------------------------------------------------------
-- CHECKERS CONTEST PLAYERS
-- Exactly two rows per booked/in-progress contest: seat 0 = host, seat 1 = challenger.
-- ----------------------------------------------------------------------------

create table public.checkers_contest_players (
  id          uuid primary key default gen_random_uuid(),
  contest_id  uuid not null references public.checkers_contests (id) on delete cascade,
  user_id     uuid not null references public.profiles (id),
  seat        smallint not null check (seat in (0, 1)),  -- 0=host, 1=challenger
  color       text not null check (color in ('black', 'white')),
  joined_at   timestamptz not null default now(),
  unique (contest_id, user_id),
  unique (contest_id, seat)
);

comment on table public.checkers_contest_players is
  'Players seated in a checkers contest. Two rows max per contest (1v1).';

create index checkers_contest_players_contest_idx on public.checkers_contest_players (contest_id);
create index checkers_contest_players_user_idx    on public.checkers_contest_players (user_id);

-- ----------------------------------------------------------------------------
-- DAILY TRIAL QUOTAS
-- Server-side enforced daily free-match limit: 3 per user per variant per day.
-- The client-side TrialManager in Modules.js tracks this locally; this table
-- is the authoritative server-side mirror used for verification before booking.
-- ----------------------------------------------------------------------------

create table public.checkers_trial_usage (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles (id) on delete cascade,
  variant     public.checkers_variant not null,
  usage_date  date not null default current_date,
  match_count smallint not null default 0 check (match_count >= 0),
  unique (user_id, variant, usage_date)
);

comment on table public.checkers_trial_usage is
  'Tracks how many free trial matches a user has played per variant per day. Max 3.';

create index checkers_trial_usage_user_date_idx
  on public.checkers_trial_usage (user_id, usage_date);

-- ----------------------------------------------------------------------------
-- FUNCTIONS
-- ----------------------------------------------------------------------------

-- Generate a random 6-char room code.
create function public.generate_room_code()
returns text
language sql
as $$
  select upper(substring(md5(random()::text) from 1 for 6));
$$;

-- Called by trigger: auto-assign room_code on contest insert.
create function public.set_room_code()
returns trigger
language plpgsql
as $$
declare
  code text;
  attempts int := 0;
begin
  loop
    code := public.generate_room_code();
    -- Retry on collision (extremely rare but handled)
    begin
      new.room_code := code;
      return new;
    exception when unique_violation then
      attempts := attempts + 1;
      if attempts > 10 then
        raise exception 'Could not generate unique room code after 10 attempts';
      end if;
    end;
  end loop;
end;
$$;

create trigger checkers_contests_set_room_code
  before insert on public.checkers_contests
  for each row
  when (new.room_code is null or new.room_code = '')
  execute procedure public.set_room_code();

-- ---------------------------------------------------------------------------
-- join_checkers_contest(contest_id, challenger_id)
-- Atomic booking: checks balance, deducts stake, flips status to 'booked'.
-- Returns: 'ok' | 'insufficient_funds' | 'already_full' | 'not_found' | 'trial_limit_reached'
-- ---------------------------------------------------------------------------

create function public.join_checkers_contest(
  p_contest_id  uuid,
  p_user_id     uuid
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_contest     public.checkers_contests%rowtype;
  v_wallet      public.wallets%rowtype;
  v_trial       public.checkers_trial_usage%rowtype;
  v_seat_count  int;
begin
  -- 1. Lock the contest row for update to prevent race conditions
  select * into v_contest
  from public.checkers_contests
  where id = p_contest_id
  for update;

  if not found then
    return 'not_found';
  end if;

  if v_contest.status <> 'open' then
    return 'already_full';
  end if;

  -- 2. Ensure challenger isn't the host
  if v_contest.host_id = p_user_id then
    return 'already_full';
  end if;

  -- 3. Free trial check (only for free contests)
  if v_contest.entry_fee_cents = 0 then
    select * into v_trial
    from public.checkers_trial_usage
    where user_id = p_user_id
      and variant = v_contest.variant
      and usage_date = current_date;

    if found and v_trial.match_count >= 3 then
      return 'trial_limit_reached';
    end if;
  end if;

  -- 4. Balance check for paid contests
  if v_contest.entry_fee_cents > 0 then
    select * into v_wallet
    from public.wallets
    where user_id = p_user_id
    for update;

    if not found or (v_wallet.balance_cents - v_wallet.locked_cents) < v_contest.entry_fee_cents then
      return 'insufficient_funds';
    end if;

    -- Deduct challenger stake
    update public.wallets
    set balance_cents = balance_cents - v_contest.entry_fee_cents,
        updated_at    = now()
    where user_id = p_user_id;

    -- Record stake transaction
    insert into public.transactions (user_id, match_id, type, status, amount_cents)
    values (p_user_id, null, 'stake', 'completed', v_contest.entry_fee_cents);
  end if;

  -- 5. Seat the challenger (seat 1, color 'white'; host is seat 0, 'black')
  insert into public.checkers_contest_players (contest_id, user_id, seat, color)
  values (p_contest_id, p_user_id, 1, 'white');

  -- 6. Lock the contest
  update public.checkers_contests
  set status    = 'booked',
      pot_cents = pot_cents + v_contest.entry_fee_cents,
      booked_at = now()
  where id = p_contest_id;

  -- 7. Increment trial counter
  if v_contest.entry_fee_cents = 0 then
    insert into public.checkers_trial_usage (user_id, variant, usage_date, match_count)
    values (p_user_id, v_contest.variant, current_date, 1)
    on conflict (user_id, variant, usage_date)
    do update set match_count = checkers_trial_usage.match_count + 1;
  end if;

  return 'ok';
end;
$$;

-- ---------------------------------------------------------------------------
-- host_checkers_contest(host_id, variant, theme, entry_fee_cents)
-- Creates a contest and seats the host. Deducts stake if paid.
-- Returns: contest_id (uuid) cast to text, or error string prefixed with 'err:'
-- ---------------------------------------------------------------------------

create function public.host_checkers_contest(
  p_host_id         uuid,
  p_variant         public.checkers_variant,
  p_theme           public.checkers_theme,
  p_entry_fee_cents bigint
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_wallet      public.wallets%rowtype;
  v_trial       public.checkers_trial_usage%rowtype;
  v_contest_id  uuid;
begin
  -- Free trial limit check
  if p_entry_fee_cents = 0 then
    select * into v_trial
    from public.checkers_trial_usage
    where user_id = p_host_id
      and variant = p_variant
      and usage_date = current_date;

    if found and v_trial.match_count >= 3 then
      return 'err:trial_limit_reached';
    end if;
  end if;

  -- Balance check for paid contests
  if p_entry_fee_cents > 0 then
    select * into v_wallet
    from public.wallets
    where user_id = p_host_id
    for update;

    if not found or (v_wallet.balance_cents - v_wallet.locked_cents) < p_entry_fee_cents then
      return 'err:insufficient_funds';
    end if;

    update public.wallets
    set balance_cents = balance_cents - p_entry_fee_cents,
        updated_at    = now()
    where user_id = p_host_id;

    insert into public.transactions (user_id, match_id, type, status, amount_cents)
    values (p_host_id, null, 'stake', 'completed', p_entry_fee_cents);
  end if;

  -- Create contest (room_code auto-generated by trigger)
  insert into public.checkers_contests (host_id, variant, theme, entry_fee_cents, pot_cents, room_code)
  values (p_host_id, p_variant, p_theme, p_entry_fee_cents, p_entry_fee_cents, '')
  returning id into v_contest_id;

  -- Seat host as seat 0, color 'black' (moves first per checkers standard)
  insert into public.checkers_contest_players (contest_id, user_id, seat, color)
  values (v_contest_id, p_host_id, 0, 'black');

  -- Increment free trial counter for host
  if p_entry_fee_cents = 0 then
    insert into public.checkers_trial_usage (user_id, variant, usage_date, match_count)
    values (p_host_id, p_variant, current_date, 1)
    on conflict (user_id, variant, usage_date)
    do update set match_count = checkers_trial_usage.match_count + 1;
  end if;

  return v_contest_id::text;
end;
$$;

-- ---------------------------------------------------------------------------
-- complete_checkers_contest(contest_id, winner_id)
-- Marks contest complete and pays out winner. Called by trusted backend.
-- ---------------------------------------------------------------------------

create function public.complete_checkers_contest(
  p_contest_id  uuid,
  p_winner_id   uuid   -- null = draw → refund both
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_contest  public.checkers_contests%rowtype;
  v_player   record;
begin
  select * into v_contest
  from public.checkers_contests
  where id = p_contest_id
  for update;

  if not found or v_contest.status not in ('booked', 'in_progress') then
    return;
  end if;

  update public.checkers_contests
  set status       = 'completed',
      winner_id    = p_winner_id,
      completed_at = now()
  where id = p_contest_id;

  -- Payout winner, or refund both on draw
  if p_winner_id is not null then
    -- Winner gets full pot
    update public.wallets
    set balance_cents = balance_cents + v_contest.pot_cents,
        updated_at    = now()
    where user_id = p_winner_id;

    insert into public.transactions (user_id, match_id, type, status, amount_cents)
    values (p_winner_id, null, 'payout', 'completed', v_contest.pot_cents);
  else
    -- Draw: refund each player their stake
    for v_player in
      select user_id from public.checkers_contest_players where contest_id = p_contest_id
    loop
      update public.wallets
      set balance_cents = balance_cents + v_contest.entry_fee_cents,
          updated_at    = now()
      where user_id = v_player.user_id;

      insert into public.transactions (user_id, match_id, type, status, amount_cents)
      values (v_player.user_id, null, 'refund', 'completed', v_contest.entry_fee_cents);
    end loop;
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- get_trial_remaining(user_id, variant) → smallint
-- Convenience RPC: returns how many free trial matches remain today.
-- ---------------------------------------------------------------------------

create function public.get_checkers_trial_remaining(
  p_user_id uuid,
  p_variant public.checkers_variant
)
returns smallint
language sql
security definer
set search_path = public
stable
as $$
  select coalesce(
    3 - (
      select match_count from public.checkers_trial_usage
      where user_id = p_user_id
        and variant = p_variant
        and usage_date = current_date
    ),
    3
  )::smallint;
$$;

-- ---------------------------------------------------------------------------
-- get_open_checkers_contests() → table
-- Real-time list of open contests with host username for the lobby.
-- ---------------------------------------------------------------------------

create function public.get_open_checkers_contests()
returns table (
  id              uuid,
  host_username   text,
  variant         public.checkers_variant,
  theme           public.checkers_theme,
  entry_fee_cents bigint,
  room_code       text,
  created_at      timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select
    c.id,
    p.username as host_username,
    c.variant,
    c.theme,
    c.entry_fee_cents,
    c.room_code,
    c.created_at
  from public.checkers_contests c
  join public.profiles p on p.id = c.host_id
  where c.status = 'open'
  order by c.created_at desc;
$$;

-- ----------------------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ----------------------------------------------------------------------------

alter table public.checkers_contests         enable row level security;
alter table public.checkers_contest_players  enable row level security;
alter table public.checkers_trial_usage      enable row level security;

-- Contests: everyone can read open/booked contests; only host or admin updates
create policy "Checkers contests viewable by all"
  on public.checkers_contests for select using (true);

create policy "Authenticated users can host a contest"
  on public.checkers_contests for insert
  with check (auth.uid() = host_id);

create policy "Host or admin can update contest"
  on public.checkers_contests for update
  using (auth.uid() = host_id or public.is_admin());

-- Players: everyone reads, own rows only for insert
create policy "Contest players viewable by all"
  on public.checkers_contest_players for select using (true);

create policy "Users can seat themselves"
  on public.checkers_contest_players for insert
  with check (auth.uid() = user_id);

-- Trial usage: own rows only
create policy "Users can view their own trial usage"
  on public.checkers_trial_usage for select
  using (auth.uid() = user_id);

-- Note: trial_usage inserts/updates are done inside the security-definer
-- functions above, so no public DML policy is needed.
