-- ============================================================================
-- Migration: 0008_ludo_matchmaking.sql
-- Purpose:   Variant/theme manager, matchmaking, wallet verification, booking
--            system, daily trial quota, and leave/forfeit handling for the
--            Ludo game integration.
--
-- This intentionally mirrors the structure of 0004_checkers_matchmaking.sql
-- and 0005_checkers_leave_forfeit.sql as closely as the game shape allows.
-- The main structural difference from checkers: a Ludo contest seats 2-4
-- players (not a fixed 1v1), so `max_players` is chosen by the host and the
-- contest only flips from 'open' to 'booked' once every seat is filled.
-- Reuses public.contest_status (defined in 0004_checkers_matchmaking.sql) —
-- the lifecycle (open → booked → in_progress → completed | cancelled) is
-- identical, so no new enum is created for it.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- ENUM EXTENSIONS
-- ----------------------------------------------------------------------------

-- Ludo board/token themes (mirrors ThemeManager THEMES keys in public/ludo/js/Modules.js)
create type public.ludo_theme as enum ('classic', 'royal', 'sunset', 'ocean');

-- Token colors, in fixed turn order (matches COLORS in public/ludo/js/GameEngine.js)
create type public.ludo_color as enum ('red', 'green', 'yellow', 'blue');

-- ----------------------------------------------------------------------------
-- LUDO CONTESTS
-- A contest is a hosted Ludo match for 2-4 players with a theme and optional
-- entry fee. 'open' means the host is still waiting for seats to fill.
-- 'booked' means every seat (max_players) is filled and locked.
-- ----------------------------------------------------------------------------

create table public.ludo_contests (
  id              uuid primary key default gen_random_uuid(),
  host_id         uuid not null references public.profiles (id) on delete cascade,
  theme           public.ludo_theme not null default 'classic',
  max_players     smallint not null default 4 check (max_players in (2, 3, 4)),

  -- Entry fee in KES cents. 0 = Free Trial match.
  entry_fee_cents bigint not null default 0 check (entry_fee_cents >= 0),

  -- Accumulated pot. For a free match: 0. Otherwise entry_fee_cents × seated players.
  pot_cents       bigint not null default 0 check (pot_cents >= 0),

  status          public.contest_status not null default 'open',

  -- Winner set on completion; null if cancelled.
  winner_id       uuid references public.profiles (id),

  -- Set when a seated player leaves an open/booked/in_progress contest.
  forfeited_by    uuid references public.profiles (id),

  -- Room code for direct invite (6-char uppercase alphanum). Generated by trigger.
  room_code       text not null unique,

  created_at      timestamptz not null default now(),
  booked_at       timestamptz,
  started_at      timestamptz,
  completed_at    timestamptz
);

comment on table public.ludo_contests is
  'Hosted Ludo contests. Each row is one 2-4 player match with theme + stake.';

create index ludo_contests_status_idx    on public.ludo_contests (status);
create index ludo_contests_host_idx      on public.ludo_contests (host_id);
create index ludo_contests_created_idx   on public.ludo_contests (created_at desc);

-- ----------------------------------------------------------------------------
-- LUDO CONTEST PLAYERS
-- Up to four rows per contest. seat 0 = host (always 'red'), seats 1-3 fill
-- in join order with 'green', 'yellow', 'blue' respectively.
-- ----------------------------------------------------------------------------

create table public.ludo_contest_players (
  id          uuid primary key default gen_random_uuid(),
  contest_id  uuid not null references public.ludo_contests (id) on delete cascade,
  user_id     uuid not null references public.profiles (id),
  seat        smallint not null check (seat in (0, 1, 2, 3)),
  color       public.ludo_color not null,
  left_at     timestamptz,  -- set when this player forfeits mid-match
  joined_at   timestamptz not null default now(),
  unique (contest_id, user_id),
  unique (contest_id, seat)
);

comment on table public.ludo_contest_players is
  'Players seated in a Ludo contest. Up to four rows per contest.';

create index ludo_contest_players_contest_idx on public.ludo_contest_players (contest_id);
create index ludo_contest_players_user_idx    on public.ludo_contest_players (user_id);

-- ----------------------------------------------------------------------------
-- DAILY TRIAL QUOTAS
-- Server-side enforced daily free-match limit: 3 per user per day for Ludo
-- (no variant split, unlike checkers' english/russian — Ludo has one ruleset).
-- ----------------------------------------------------------------------------

create table public.ludo_trial_usage (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles (id) on delete cascade,
  usage_date  date not null default current_date,
  match_count smallint not null default 0 check (match_count >= 0),
  unique (user_id, usage_date)
);

comment on table public.ludo_trial_usage is
  'Tracks how many free trial Ludo matches a user has played per day. Max 3.';

create index ludo_trial_usage_user_date_idx
  on public.ludo_trial_usage (user_id, usage_date);

-- ----------------------------------------------------------------------------
-- FUNCTIONS
-- ----------------------------------------------------------------------------

-- Called by trigger: auto-assign room_code on contest insert.
-- Reuses public.generate_room_code() defined in 0004_checkers_matchmaking.sql.
create function public.set_ludo_room_code()
returns trigger
language plpgsql
as $$
declare
  code text;
  attempts int := 0;
begin
  loop
    code := public.generate_room_code();
    begin
      new.room_code := code;
      return new;
    exception when unique_violation then
      attempts := attempts + 1;
      if attempts > 10 then
        raise exception 'Could not generate unique room code after 10 attempts';
      end if;
    end;
  end loop;
end;
$$;

create trigger ludo_contests_set_room_code
  before insert on public.ludo_contests
  for each row
  when (new.room_code is null or new.room_code = '')
  execute procedure public.set_ludo_room_code();

-- ---------------------------------------------------------------------------
-- host_ludo_contest(host_id, theme, max_players, entry_fee_cents)
-- Creates a contest and seats the host at seat 0 ('red'). Deducts stake if paid.
-- Returns: contest_id (uuid) cast to text, or error string prefixed with 'err:'
-- ---------------------------------------------------------------------------

create function public.host_ludo_contest(
  p_host_id         uuid,
  p_theme           public.ludo_theme,
  p_max_players     smallint,
  p_entry_fee_cents bigint
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_wallet      public.wallets%rowtype;
  v_trial       public.ludo_trial_usage%rowtype;
  v_contest_id  uuid;
begin
  if p_max_players not in (2, 3, 4) then
    return 'err:invalid_player_count';
  end if;

  -- Free trial limit check
  if p_entry_fee_cents = 0 then
    select * into v_trial
    from public.ludo_trial_usage
    where user_id = p_host_id
      and usage_date = current_date;

    if found and v_trial.match_count >= 3 then
      return 'err:trial_limit_reached';
    end if;
  end if;

  -- Balance check for paid contests
  if p_entry_fee_cents > 0 then
    select * into v_wallet
    from public.wallets
    where user_id = p_host_id
    for update;

    if not found or (v_wallet.balance_cents - v_wallet.locked_cents) < p_entry_fee_cents then
      return 'err:insufficient_funds';
    end if;

    update public.wallets
    set balance_cents = balance_cents - p_entry_fee_cents,
        updated_at    = now()
    where user_id = p_host_id;

    insert into public.transactions (user_id, match_id, type, status, amount_cents)
    values (p_host_id, null, 'stake', 'completed', p_entry_fee_cents);
  end if;

  -- Create contest (room_code auto-generated by trigger)
  insert into public.ludo_contests (host_id, theme, max_players, entry_fee_cents, pot_cents, room_code)
  values (p_host_id, p_theme, p_max_players, p_entry_fee_cents, p_entry_fee_cents, '')
  returning id into v_contest_id;

  -- Seat host as seat 0, color 'red' (moves first per Ludo turn order)
  insert into public.ludo_contest_players (contest_id, user_id, seat, color)
  values (v_contest_id, p_host_id, 0, 'red');

  -- Increment free trial counter for host
  if p_entry_fee_cents = 0 then
    insert into public.ludo_trial_usage (user_id, usage_date, match_count)
    values (p_host_id, current_date, 1)
    on conflict (user_id, usage_date)
    do update set match_count = ludo_trial_usage.match_count + 1;
  end if;

  return v_contest_id::text;
end;
$$;

-- ---------------------------------------------------------------------------
-- join_ludo_contest(contest_id, user_id)
-- Atomic seating: checks balance/trial, deducts stake, takes the next free
-- seat, and flips status to 'booked' once max_players is reached.
-- Returns: 'ok' | 'insufficient_funds' | 'already_full' | 'not_found' | 'trial_limit_reached'
-- ---------------------------------------------------------------------------

create function public.join_ludo_contest(
  p_contest_id  uuid,
  p_user_id     uuid
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_contest     public.ludo_contests%rowtype;
  v_wallet      public.wallets%rowtype;
  v_trial       public.ludo_trial_usage%rowtype;
  v_seat_count  int;
  v_next_seat   smallint;
  v_color       public.ludo_color;
  v_colors      public.ludo_color[] := array['red', 'green', 'yellow', 'blue'];
begin
  select * into v_contest
  from public.ludo_contests
  where id = p_contest_id
  for update;

  if not found then
    return 'not_found';
  end if;

  if v_contest.status <> 'open' then
    return 'already_full';
  end if;

  if exists (
    select 1 from public.ludo_contest_players
    where contest_id = p_contest_id and user_id = p_user_id
  ) then
    return 'already_full';
  end if;

  select count(*) into v_seat_count
  from public.ludo_contest_players
  where contest_id = p_contest_id;

  if v_seat_count >= v_contest.max_players then
    return 'already_full';
  end if;

  -- Free trial check (only for free contests)
  if v_contest.entry_fee_cents = 0 then
    select * into v_trial
    from public.ludo_trial_usage
    where user_id = p_user_id
      and usage_date = current_date;

    if found and v_trial.match_count >= 3 then
      return 'trial_limit_reached';
    end if;
  end if;

  -- Balance check for paid contests
  if v_contest.entry_fee_cents > 0 then
    select * into v_wallet
    from public.wallets
    where user_id = p_user_id
    for update;

    if not found or (v_wallet.balance_cents - v_wallet.locked_cents) < v_contest.entry_fee_cents then
      return 'insufficient_funds';
    end if;

    update public.wallets
    set balance_cents = balance_cents - v_contest.entry_fee_cents,
        updated_at    = now()
    where user_id = p_user_id;

    insert into public.transactions (user_id, match_id, type, status, amount_cents)
    values (p_user_id, null, 'stake', 'completed', v_contest.entry_fee_cents);
  end if;

  v_next_seat := v_seat_count; -- 0-indexed, host already took seat 0
  v_color     := v_colors[v_next_seat + 1]; -- postgres arrays are 1-indexed

  insert into public.ludo_contest_players (contest_id, user_id, seat, color)
  values (p_contest_id, p_user_id, v_next_seat, v_color);

  -- Increment trial counter
  if v_contest.entry_fee_cents = 0 then
    insert into public.ludo_trial_usage (user_id, usage_date, match_count)
    values (p_user_id, current_date, 1)
    on conflict (user_id, usage_date)
    do update set match_count = ludo_trial_usage.match_count + 1;
  end if;

  -- Lock the contest once every seat is filled
  if v_seat_count + 1 >= v_contest.max_players then
    update public.ludo_contests
    set status    = 'booked',
        pot_cents = v_contest.entry_fee_cents * (v_seat_count + 1),
        booked_at = now()
    where id = p_contest_id;
  end if;

  return 'ok';
end;
$$;

-- ---------------------------------------------------------------------------
-- leave_ludo_contest(contest_id, user_id)
-- Mirrors leave_checkers_contest():
--   - Still 'open' (lobby not full yet): leaving removes that seat and
--     refunds that player's own stake. If the host leaves, the whole
--     contest is cancelled and every seated player is refunded.
--   - 'booked'/'in_progress': leaving forfeits that player. If only one
--     non-forfeited player remains, they're declared the winner and the
--     pot is paid out; otherwise the match continues for the rest.
-- Returns: 'cancelled' | 'left' | 'forfeited' | 'completed' | 'not_found'
--          | 'not_a_player' | 'already_over' | 'error'
-- ---------------------------------------------------------------------------

create function public.leave_ludo_contest(
  p_contest_id  uuid,
  p_user_id     uuid
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_contest        public.ludo_contests%rowtype;
  v_is_player      boolean;
  v_remaining_cnt  int;
  v_last_player    uuid;
  v_seated         record;
begin
  select * into v_contest
  from public.ludo_contests
  where id = p_contest_id
  for update;

  if not found then
    return 'not_found';
  end if;

  select exists (
    select 1 from public.ludo_contest_players
    where contest_id = p_contest_id and user_id = p_user_id
  ) into v_is_player;

  if not v_is_player then
    return 'not_a_player';
  end if;

  if v_contest.status in ('completed', 'cancelled') then
    return 'already_over';
  end if;

  -- ── Still open: lobby hasn't filled ─────────────────────────────────────
  if v_contest.status = 'open' then
    if v_contest.host_id = p_user_id then
      -- Host leaving cancels the whole lobby; refund everyone seated.
      if v_contest.entry_fee_cents > 0 then
        for v_seated in
          select user_id from public.ludo_contest_players where contest_id = p_contest_id
        loop
          update public.wallets
          set balance_cents = balance_cents + v_contest.entry_fee_cents,
              updated_at    = now()
          where user_id = v_seated.user_id;

          insert into public.transactions (user_id, match_id, type, status, amount_cents)
          values (v_seated.user_id, null, 'refund', 'completed', v_contest.entry_fee_cents);
        end loop;
      end if;

      update public.ludo_contests
      set status       = 'cancelled',
          forfeited_by = p_user_id,
          completed_at = now()
      where id = p_contest_id;

      return 'cancelled';
    end if;

    -- A non-host challenger leaving the still-open lobby: refund just them
    -- and free their seat so others can still join.
    if v_contest.entry_fee_cents > 0 then
      update public.wallets
      set balance_cents = balance_cents + v_contest.entry_fee_cents,
          updated_at    = now()
      where user_id = p_user_id;

      insert into public.transactions (user_id, match_id, type, status, amount_cents)
      values (p_user_id, null, 'refund', 'completed', v_contest.entry_fee_cents);
    end if;

    delete from public.ludo_contest_players
    where contest_id = p_contest_id and user_id = p_user_id;

    return 'left';
  end if;

  -- ── Booked / in_progress: forfeit this seat ─────────────────────────────
  update public.ludo_contest_players
  set left_at = now()
  where contest_id = p_contest_id and user_id = p_user_id and left_at is null;

  select count(*) into v_remaining_cnt
  from public.ludo_contest_players
  where contest_id = p_contest_id and left_at is null;

  if v_remaining_cnt <= 1 then
    select user_id into v_last_player
    from public.ludo_contest_players
    where contest_id = p_contest_id and left_at is null
    limit 1;

    update public.ludo_contests
    set status       = 'completed',
        winner_id    = v_last_player,
        forfeited_by = p_user_id,
        completed_at = now()
    where id = p_contest_id;

    if v_last_player is not null and v_contest.pot_cents > 0 then
      update public.wallets
      set balance_cents = balance_cents + v_contest.pot_cents,
          updated_at    = now()
      where user_id = v_last_player;

      insert into public.transactions (user_id, match_id, type, status, amount_cents)
      values (v_last_player, null, 'payout', 'completed', v_contest.pot_cents);
    end if;

    return 'completed';
  end if;

  -- More than one active player remains — flag the forfeit and let the
  -- match continue. The client engine's turn manager skips left-seats.
  update public.ludo_contests
  set forfeited_by = p_user_id
  where id = p_contest_id;

  return 'forfeited';
exception
  when others then
    return 'error';
end;
$$;

comment on function public.leave_ludo_contest is
  'Player leaves a Ludo contest. Cancels/refunds if still open (host) or removes just that seat (non-host); forfeits the seat and may end the match if booked/in_progress.';

-- ---------------------------------------------------------------------------
-- complete_ludo_contest(contest_id, winner_id)
-- Marks contest complete and pays out the winner. Skips wallet/ledger writes
-- for zero-stake matches from the start (see 0007_checkers_zero_stake_payout_fix.sql
-- for why that guard matters — applied here up front rather than as a patch).
-- ---------------------------------------------------------------------------

create function public.complete_ludo_contest(
  p_contest_id  uuid,
  p_winner_id   uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_contest  public.ludo_contests%rowtype;
begin
  select * into v_contest
  from public.ludo_contests
  where id = p_contest_id
  for update;

  if not found or v_contest.status not in ('booked', 'in_progress') then
    return;
  end if;

  update public.ludo_contests
  set status       = 'completed',
      winner_id    = p_winner_id,
      completed_at = now()
  where id = p_contest_id;

  if p_winner_id is not null and v_contest.pot_cents > 0 then
    update public.wallets
    set balance_cents = balance_cents + v_contest.pot_cents,
        updated_at    = now()
    where user_id = p_winner_id;

    insert into public.transactions (user_id, match_id, type, status, amount_cents)
    values (p_winner_id, null, 'payout', 'completed', v_contest.pot_cents);
  end if;
end;
$$;

comment on function public.complete_ludo_contest is
  'Marks a Ludo contest complete and pays out the winner. No-op for zero-stake matches beyond marking status.';

-- ---------------------------------------------------------------------------
-- get_ludo_trial_remaining(user_id) → smallint
-- ---------------------------------------------------------------------------

create function public.get_ludo_trial_remaining(
  p_user_id uuid
)
returns smallint
language sql
security definer
set search_path = public
stable
as $$
  select coalesce(
    3 - (
      select match_count from public.ludo_trial_usage
      where user_id = p_user_id
        and usage_date = current_date
    ),
    3
  )::smallint;
$$;

-- ---------------------------------------------------------------------------
-- get_open_ludo_contests() → table
-- Real-time list of open contests with host username + current seat count
-- for the lobby (so the UI can show "2/4 seated" etc.).
-- ---------------------------------------------------------------------------

create function public.get_open_ludo_contests()
returns table (
  id              uuid,
  host_username   text,
  theme           public.ludo_theme,
  max_players     smallint,
  seated_players  bigint,
  entry_fee_cents bigint,
  room_code       text,
  created_at      timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select
    c.id,
    p.username as host_username,
    c.theme,
    c.max_players,
    (select count(*) from public.ludo_contest_players cp where cp.contest_id = c.id) as seated_players,
    c.entry_fee_cents,
    c.room_code,
    c.created_at
  from public.ludo_contests c
  join public.profiles p on p.id = c.host_id
  where c.status = 'open'
  order by c.created_at desc;
$$;

-- ----------------------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ----------------------------------------------------------------------------

alter table public.ludo_contests         enable row level security;
alter table public.ludo_contest_players  enable row level security;
alter table public.ludo_trial_usage      enable row level security;

create policy "Ludo contests viewable by all"
  on public.ludo_contests for select using (true);

create policy "Authenticated users can host a ludo contest"
  on public.ludo_contests for insert
  with check (auth.uid() = host_id);

create policy "Host or admin can update ludo contest"
  on public.ludo_contests for update
  using (auth.uid() = host_id or public.is_admin());

create policy "Ludo contest players viewable by all"
  on public.ludo_contest_players for select using (true);

create policy "Users can seat themselves in ludo"
  on public.ludo_contest_players for insert
  with check (auth.uid() = user_id);

create policy "Users can view their own ludo trial usage"
  on public.ludo_trial_usage for select
  using (auth.uid() = user_id);

-- Note: trial_usage inserts/updates and contest_players deletes are done
-- inside the security-definer functions above, so no further public DML
-- policy is needed.
